In [1]:
#include <iostream>

/*a workaround to solve cling issue*/
#include "../inc/macos_cling_workaround.hpp"
/*set libtorch path, load libs*/
#include "../inc/load_libtorch.hpp"
/*import custom defined macros*/
#include "../inc/custom_def.hpp"
/*import matplotlibcpp*/
#include "../inc/load_matplotlibcpp.hpp"
/*import opencv*/
#include "../inc/load_opencv.hpp"

/*import libtorch header file*/
#include <torch/torch.h>
#include <opencv2/opencv.hpp>
#include <cmath>



std::cout << std::boolalpha;

// Use (void) to silent unused warnings.
#define assertm(exp, msg) assert(((void)msg, exp))

@0x7fe38536eb60

In [2]:
#define VAR_NAME(Variable) (#Variable)

void print_tensor_size(std::string name, torch::Tensor t)
{
    int dims = t.dim();
    std::cout << name << " dims is (";
    for (int i = 0; i < dims; i++) {
        std::cout << t.size(i);
        if (i < (dims - 1)) std::cout << " x ";
    }
    std::cout << ")" << std::endl;
}

In [3]:
!nvidia-smi

Mon Apr 26 10:52:21 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.181.07   Driver Version: 418.181.07   CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0 Off |                  N/A |
| 29%   44C    P0    29W / 120W |   1151MiB /  6078MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

**计算设备**

In [4]:
// torch.device('cpu'), torch.cuda.device('cuda'), torch.cuda.device('cuda:1')

///https://pytorch.org/cppdocs/api/structc10_1_1_device.html#_CPPv4N3c106DeviceE

torch::Device device_c = torch::kCPU;

torch::Device device_gpu = torch::kCUDA;

device_gpu.set_index(0);
//如果有多个gpu，还可以设置其它值，eg:
//device_gpu.set_index(1);

**查询可用gpu的数量**

In [5]:
printT(torch::cuda::is_available());
printT(torch::cuda::device_count());

torch::cuda::is_available() = 
true
<<--->>

torch::cuda::device_count() = 
1
<<--->>



**这两个函数允许我们在请求的GPU不存在的情况下运行代码**

In [6]:
torch::Device try_gpu(int i=0)
{
    std::cout << "calling try_gpu() ..." << std::endl;
    if (torch::cuda::device_count() >= (i+1)) {
        return torch::Device(torch::kCUDA, i);
    }
    
    std::cout << "no gpu found!" << std::endl;
    return torch::Device("cpu");
}

In [7]:
void try_all_gpus()
{
    std::cout << "calling try_all_gpus() ..." << std::endl;
    std::vector<torch::Device> devices;

    if (torch::cuda::device_count()) {
        int c = torch::cuda::device_count();
        std::cout << "total gpu count is : " << torch::cuda::device_count() << std::endl;
        for (int i = 0; i < c; i++) {
            devices.push_back(torch::Device(torch::kCUDA, i));
        }
    } else {
        devices.push_back(torch::Device("cpu"));
    }
    return devices;
}

In [8]:
try_gpu();

calling try_gpu() ...


In [9]:
try_gpu(10);

calling try_gpu() ...
no gpu found!


In [10]:
try_all_gpus();

calling try_all_gpus() ...
total gpu count is : 1


**查询张量所在的设备**

In [11]:
auto x = torch::tensor({1, 2, 3});
printT(x.device());

x.device() = 
cpu
<<--->>



**存储在GPU上**

In [12]:
auto X = torch::ones({2, 3}, try_gpu());
printT(X);
printT(X.device());

calling try_gpu() ...
X = 
 1  1  1
 1  1  1
[ CUDAFloatType{2,3} ]
<<--->>

X.device() = 
cuda:0
<<--->>



**第二个GPU上创建一个随机张量**

注：本人机器没有第二张GPU，因此只能用cuda：0。。。

In [13]:
auto Y = torch::rand({2, 3}, try_gpu(0));
printT(Y);
printT(Y.device());

calling try_gpu() ...
Y = 
 0.9221  0.5072  0.3604
 0.1224  0.2166  0.6024
[ CUDAFloatType{2,3} ]
<<--->>

Y.device() = 
cuda:0
<<--->>



**要计算X + Y，我们需要决定在哪里执行这个操作**

In [14]:
auto Z = X.to(torch::kCUDA);
printT(X);
printT(X.device());
printT(Z);
printT(Z.device());

X = 
 1  1  1
 1  1  1
[ CUDAFloatType{2,3} ]
<<--->>

X.device() = 
cuda:0
<<--->>

Z = 
 1  1  1
 1  1  1
[ CUDAFloatType{2,3} ]
<<--->>

Z.device() = 
cuda:0
<<--->>



**现在数据在同一个GPU上（Z和Y都在），我们可以将它们相加**

In [15]:
printT(Y + Z);

Y + Z = 
 1.9221  1.5072  1.3604
 1.1224  1.2166  1.6024
[ CUDAFloatType{2,3} ]
<<--->>



In [16]:
printT(Z.to(torch::kCUDA).equal(Z));

Z.to(torch::kCUDA).equal(Z) = 
true
<<--->>



**神经网络与GPU**

In [17]:
torch::nn::Sequential net(torch::nn::Linear(3, 1));
net->to(try_gpu());

printT(net->forward(X));

calling try_gpu() ...
net->forward(X) = 
0.01 *
-3.5769
 -3.5769
[ CUDAFloatType{2,1} ]
<<--->>



**确认模型参数存储在同一个GPU上**

In [18]:
// net[0].weight.data.device
auto od = net[0]->named_parameters();
auto w = od.find("weight");

if(w != nullptr) {
    printT(w->device());
}

w->device() = 
cuda:0
<<--->>

