In [2]:
#include <iostream>

/*a workaround to solve cling issue*/
#include "../inc/macos_cling_workaround.hpp"
/*set libtorch path, load libs*/
#include "../inc/load_libtorch.hpp"
/*import custom defined macros*/
#include "../inc/custom_def.hpp"
/*import libtorch header file*/
#include <torch/torch.h>

# 1.创建一个Tensor

## 1.1 创建一个新的Tensor，以empty函数为例：

In [3]:
torch::Tensor t1 = torch::empty(3, torch::kInt64);

std::cout << t1 << std::endl;

 8.2420e+18
 7.0184e+18
 7.8127e+18
[ CPULongType{3} ]


In [4]:
torch::Tensor t1 = torch::empty(3, torch::kCPU);

std::cout << t1 << std::endl;

 1.2777e-06
 4.5864e-41
 1.2777e-06
[ CPUFloatType{3} ]


In [5]:
torch::Tensor t2 = torch::empty({5,6}, torch::kInt32);
std::cout << t2 << std::endl;

 8.2971e+08  1.7179e+09  1.9533e+09  1.8186e+09  1.2314e+09  1.1639e+09
 8.2649e+08  8.4432e+08  1.5972e+09  1.9497e+09  1.7513e+09  1.9538e+09
 1.6349e+09  1.0938e+09  1.7354e+09  1.2984e+09  1.1640e+09  8.2853e+08
 1.3299e+09  1.4145e+09 -1.6753e+07 -1.0000e+00  1.1300e+02  0.0000e+00
 1.5508e+09  2.2084e+04  1.5529e+09  2.2084e+04  1.5514e+09  2.2084e+04
[ CPUIntType{5,6} ]


In [6]:
torch::Device dev_cpu(torch::kCPU);
/*因为只有一块1060，因此index只能填0，填其它值会报错*/
/*macbook pro就不要尝试了，因为你没有cuda！*/
torch::Device dev_gpu(torch::kCUDA, 0/*device index*/);

torch::ScalarType dtype_int(torch::kInt);

at::IntArrayRef m_iar_1({3}); 
at::IntArrayRef m_iar_2({3,4}); 
at::ArrayRef<int64_t> m_ar_1({3});
at::ArrayRef<int64_t> m_ar_2({3,4});

torch::Tensor t1 = torch::empty(m_iar_1, dev_cpu);
std::cout << "t1 = " << std::endl << t1 << std::endl << std::endl;

torch::Tensor t2 = torch::empty(m_ar_2, dev_gpu);
std::cout << "t2 = " << std::endl << t2 << std::endl << std::endl;

torch::Tensor t3 = torch::empty(m_ar_1, dtype_int);
std::cout << "t3 = " << std::endl << t3 << std::endl << std::endl;

torch::Tensor t4 = torch::empty(m_iar_2, torch::kSparse);
std::cout << "t4 = " << std::endl << t4 << std::endl << std::endl;


torch::Tensor t5 = torch::empty(m_iar_2, at::device(at::kCUDA).dtype(torch::kByte));
std::cout << "t5 = " << std::endl << t5 << std::endl << std::endl;


t1 = 
 3.1579e+03
 7.7242e-10
 6.6971e+31
[ CPUFloatType{3} ]

t2 = 
 0  0  0  0
 0  0  0  0
 0  0  0  0
[ CUDAFloatType{3,4} ]

t3 = 
 5.7680e+08
 1.9365e+09
 2.0377e+09
[ CPUIntType{3} ]

t4 = 
[ SparseCPUFloatType{}
indices:
[ CPULongType{2,0} ]
values:
[ CPUFloatType{0} ]
size:
[3, 4]
]

t5 = 
 0  0  0  0
 0  0  0  0
 0  0  0  0
[ CUDAByteType{3,4} ]



## 1.2 创建值为0的tensor，使用zeros(...)函数

同torch::empty(...)函数一样，torch::zeros(...)函数的定义也是位于`{pytorch}/torch/csrc/autograd/generated/variable_factories.h`文件中，具体调用的，还是at::zeros(...)函数，其具体实现位于`{pytorch}/aten/src/ATen/native/TensorFactoryies.cpp`，大致的调用方式是torch::zeros(...) -> at::zeros(...) -> at::native::full(...) -> at::empty(...).fill_(...)


In [7]:
torch::Tensor x = torch::zeros(3);
std::cout << "x = " << std::endl << x << std::endl;

torch::Tensor y = torch::zeros({3, 4}, torch::kInt);
std::cout << "y = " << std::endl << y << std::endl;

x = 
 0
 0
 0
[ CPUFloatType{3} ]
y = 
 0  0  0  0
 0  0  0  0
 0  0  0  0
[ CPUIntType{3,4} ]


## 1.3 创建值为1的tensor，使用ones(...)函数

关于 ones(...) 的实现，参见 `{pytorch}/aten/src/ATen/native/TensorFactoryies.cpp`；

In [8]:
torch::Tensor x = torch::ones(5);
printT(x);

torch::Tensor y = torch::ones({3, 4}, torch::kInt);
printT(y);

x = 
 1
 1
 1
 1
 1
[ CPUFloatType{5} ]
<<--->>

y = 
 1  1  1  1
 1  1  1  1
 1  1  1  1
[ CPUIntType{3,4} ]
<<--->>



## 1.4 创建值为随机数的tensor

In [9]:
torch::Tensor x = torch::rand({3, 4});
std::cout << x << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

torch::Tensor y = torch::rand({3, 4}, torch::kFloat64);
std::cout << y << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

torch::Tensor z = torch::randn({5, 3, 4}, torch::kFloat32);
std::cout << z << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

torch::Tensor a = torch::randint(1/*low*/, 10/*high*/, {4}/*size*/, torch::kInt32);
std::cout << "a = " << std::endl << a << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

 0.3523  0.9210  0.9317  0.8193
 0.4069  0.3971  0.3080  0.7800
 0.0256  0.0208  0.7285  0.0657
[ CPUFloatType{3,4} ]
<<<=========>>>

 0.2898  0.7828  0.5083  0.6370
 0.2405  0.8166  0.7028  0.7808
 0.6381  0.2971  0.3806  0.3117
[ CPUDoubleType{3,4} ]
<<<=========>>>

(1,.,.) = 
 -0.2022 -1.3062  1.1624 -0.3078
  0.0756 -0.8598  1.0082 -0.1327
 -0.2754 -0.2268 -2.2643  1.5656

(2,.,.) = 
  0.2290 -0.4580 -0.5440  0.1151
  0.3492  1.1893 -1.3065 -0.2194
 -0.4207  0.1949  0.6551  1.5457

(3,.,.) = 
 -0.0411 -1.1133 -0.0861 -1.1201
  0.7853  0.4487 -0.6896  0.6812
  0.7853 -0.6206  0.7613 -0.6682

(4,.,.) = 
 -0.2043  0.5549  0.5182 -0.8192
 -1.4479  0.5386 -1.5750  0.1939
  0.3653 -1.2877  1.6811 -0.4075

(5,.,.) = 
 -0.7452 -0.6870  0.5630 -0.4402
  0.2659  0.7501  0.6897 -0.8028
  0.7229 -2.6378  1.5662 -1.0126
[ CPUFloatType{5,3,4} ]
<<<=========>>>

a = 
 6
 6
 5
 7
[ CPUIntType{4} ]
<<<=========>>>



## 1.5 根据已有tensor创建新的tensor

In [10]:
torch::Tensor t = torch::ones({3,3});
t += 5;

torch::Tensor a(t);
std::cout << "a = " << std::endl << a << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

a = 
 6  6  6
 6  6  6
 6  6  6
[ CPUFloatType{3,3} ]
<<<=========>>>



In [11]:
torch::Tensor a = torch::ones({5,3});
a = torch::randn_like(a);

std::cout << a << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

-1.9529 -0.1274  0.2493
 1.1422 -1.5271  0.7417
 0.9030  0.2625 -0.9188
 1.0648  0.2943 -0.4224
 0.5667  0.7336 -0.8017
[ CPUFloatType{5,3} ]
<<<=========>>>



更多例子请参考 [Tensor Creation API](https://pytorch.org/cppdocs/notes/tensor_creation.html)

# 2. Tensor的相关操作

## 2.1 加法运算

In [12]:
torch::Tensor x = torch::ones({5,3});
torch::Tensor y = torch::randn({5,3});

std::cout << "x =" << std::endl;
std::cout << (x) << std::endl << std::endl;

std::cout << "y =" << std::endl;
std::cout << (y) << std::endl << std::endl;

std::cout << "x+y =" << std::endl;
std::cout << (x+y) << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

std::cout << "torch::add(x,y) =" << std::endl;
std::cout << torch::add(x,y) << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

std::cout << "y.add_(x) =" << std::endl;
std::cout << y.add_(x) << std::endl;
std::cout << "<<<=========>>>" << std::endl << std::endl;

x =
 1  1  1
 1  1  1
 1  1  1
 1  1  1
 1  1  1
[ CPUFloatType{5,3} ]

y =
 0.3882  0.3528  0.1821
 0.5968  2.2406 -1.2372
 0.8452  1.0309 -1.0613
 1.3290 -0.4286  1.5092
 0.2170  0.3363 -0.1296
[ CPUFloatType{5,3} ]

x+y =
 1.3882  1.3528  1.1821
 1.5968  3.2406 -0.2372
 1.8452  2.0309 -0.0613
 2.3290  0.5714  2.5092
 1.2170  1.3363  0.8704
[ CPUFloatType{5,3} ]
<<<=========>>>

torch::add(x,y) =
 1.3882  1.3528  1.1821
 1.5968  3.2406 -0.2372
 1.8452  2.0309 -0.0613
 2.3290  0.5714  2.5092
 1.2170  1.3363  0.8704
[ CPUFloatType{5,3} ]
<<<=========>>>

y.add_(x) =
 1.3882  1.3528  1.1821
 1.5968  3.2406 -0.2372
 1.8452  2.0309 -0.0613
 2.3290  0.5714  2.5092
 1.2170  1.3363  0.8704
[ CPUFloatType{5,3} ]
<<<=========>>>



## 2.2 索引
借助于torch::Tensor::index()和torch::Tensor::index_put_()函数，我们可以在libtorch中实现类似pytorch中对tensor的切片存取操作。具体说明详见[tensor_indexing](https://pytorch.org/cppdocs/notes/tensor_indexing.html)页面.

In [13]:
#define SIZE (5)

torch::Tensor x = torch::zeros(SIZE);

for (int i = 0; i < SIZE; i++) {
    x[i] = i;
}
    
std::cout << "x =" << std::endl;
std::cout << (x) << std::endl << std::endl;

/* *
 *  Getter ops
 */
std::cout << "(in python) x[None]=" << std::endl;
std::cout << (x.index({torch::indexing::None})) << std::endl << std::endl;

std::cout << "(in python) x[Ellipsis, ...]=" << std::endl;
std::cout << (x.index({torch::indexing::Ellipsis, "..."})) << std::endl << std::endl;

std::cout << "(in python) x[3]=" << std::endl;
std::cout << (x.index({3})) << std::endl << std::endl;

std::cout << "(in python) x[True, False]=" << std::endl;
std::cout << (x.index({true,false,true,false,true,false,true,false,true,false,false,true,false,true,false})) << std::endl << std::endl;

std::cout << "(in python) x[1::2]=" << std::endl;
std::cout << (x.index({torch::indexing::Slice(1, torch::indexing::None, 2)})) << std::endl << std::endl;

std::cout << "(in python) x[::2]=" << std::endl;
std::cout << (x.index({torch::indexing::Slice(torch::indexing::None, torch::indexing::None, 2)})) << std::endl << std::endl;


x =
 0
 1
 2
 3
 4
[ CPUFloatType{5} ]

(in python) x[None]=
 0  1  2  3  4
[ CPUFloatType{1,5} ]

(in python) x[Ellipsis, ...]=
 0
 1
 2
 3
 4
[ CPUFloatType{5} ]

(in python) x[3]=
3
[ CPUFloatType{} ]

(in python) x[True, False]=
[ CPUFloatType{0,5} ]

(in python) x[1::2]=
 1
 3
[ CPUFloatType{2} ]

(in python) x[::2]=
 0
 2
 4
[ CPUFloatType{3} ]



In [14]:
#define SIZE (5)

torch::Tensor x = torch::zeros(SIZE);

for (int i = 0; i < SIZE; i++) {
    x[i] = i;
}
    
std::cout << "x =" << std::endl;
std::cout << (x) << std::endl << std::endl;

/* *
 *  Setter ops
 */
std::cout << "(in python) x[None] = 1" << std::endl;
std::cout << (x.index_put_({torch::indexing::None}, 1)) << std::endl << std::endl;

std::cout << "(in python) x[Ellipsis, ...] = 2" << std::endl;
std::cout << (x.index_put_({torch::indexing::Ellipsis, "..."}, 2)) << std::endl << std::endl;

std::cout << "(in python) x[3] = 3" << std::endl;
std::cout << (x.index_put_({3}, 3)) << std::endl << std::endl;

std::cout << "(in python) x[True, False] = 4" << std::endl;
std::cout << (x.index_put_({true,false,true,false,true,false,true,false,true,false,false,true,false,true,false}, 4)) << std::endl << std::endl;

std::cout << "(in python) x[1::2] = 5" << std::endl;
std::cout << (x.index_put_({torch::indexing::Slice(1, torch::indexing::None, 2)}, 5)) << std::endl << std::endl;

std::cout << "(in python) x[::2] = 6" << std::endl;
std::cout << (x.index_put_({torch::indexing::Slice(torch::indexing::None, torch::indexing::None, 2)}, 6)) << std::endl << std::endl;


x =
 0
 1
 2
 3
 4
[ CPUFloatType{5} ]

(in python) x[None] = 1
 1
 1
 1
 1
 1
[ CPUFloatType{5} ]

(in python) x[Ellipsis, ...] = 2
 2
 2
 2
 2
 2
[ CPUFloatType{5} ]

(in python) x[3] = 3
 2
 2
 2
 3
 2
[ CPUFloatType{5} ]

(in python) x[True, False] = 4
 2
 2
 2
 3
 2
[ CPUFloatType{5} ]

(in python) x[1::2] = 5
 2
 5
 2
 5
 2
[ CPUFloatType{5} ]

(in python) x[::2] = 6
 6
 5
 6
 5
 6
[ CPUFloatType{5} ]



### Python 与 C++ 索引类型对照表

|Python | C++ (assuming using namespace torch::indexing) |
|:---|:---|
|None|None|
|Ellipsis|Ellipsis|
|...|"..."|
|123|123|
|True|true|
|False|false|
|: or ::|Slice() or Slice(None, None) or Slice(None, None, None)|
|1: or 1::|Slice(1, None) or Slice(1, None, None)|
|:3 or :3:|Slice(None, 3) or Slice(None, 3, None)|
|::2|Slice(None, None, 2)|
|1:3|Slice(1, 3)|
|1::2|Slice(1, None, 2)|
|:3:2|Slice(None, 3, 2)|
|1:3:2|Slice(1, 3, 2)|
|torch.tensor([1, 2])|torch::tensor({1, 2})|

### 其它索引操作

In [15]:
torch::Tensor x = torch::zeros({3,4});

for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 4; j++) {
        x[i][j] = i*4+j;
    }
}
    
std::cout << "x =" << std::endl;
std::cout << (x) << std::endl << std::endl;


/** Warning:
 *  a known issue: with xeus-cling, if you call torch::from_blob,
 *  there will be a link error, 
 *  
 *  IncrementalExecutor::executeFunction: 
 *  symbol '__emutls_v._ZSt11__once_call' unresolved 
 *  while linking function '_GLOBAL__sub_I_cling_module_8'!
 *
 *
 *  so I write this example in pure 
 *  c++ code in folder : 'cpp_project/basic_ops'.
 */
// std::vector<int32_t> v = {1,2,7,8}; 
// auto idx = torch::from_blob(v.data(), v.size(), torch::kInt32);


std::cout << "<<< tensor.index_select >>>" << std::endl;
torch::Tensor idx = torch::arange(1,3);
std::cout << (idx) << std::endl << std::endl;

std::cout << "x.index_select(dim = 0, index = idx) =" << std::endl;
std::cout << (x.index_select(0,idx)) << std::endl << std::endl;

std::cout << "x.index_select(dim = 1, index = idx) =" << std::endl;
std::cout << (x.index_select(1,idx)) << std::endl << std::endl;


std::cout << "<<< tensor.masked_select >>>" << std::endl;
torch::Tensor mask = x > 5;
std::cout << (mask) << std::endl << std::endl;
std::cout << "x.masked_select(mask = mask) =" << std::endl;
std::cout << (x.masked_select(mask)) << std::endl << std::endl;

std::cout << "<<< tensor.nonzero >>>" << std::endl;
std::cout << "注意，返回值是非零元素下标，即x,y "<< std::endl << "x.nonzero() =" << std::endl;
std::cout << (x.nonzero()) << std::endl << std::endl;

std::cout << "<<< tensor.gather >>>" << std::endl;
std::cout << "注意，index tensor必须指明类型为int64" << std::endl;
torch::Tensor g = torch::ones({2,2}, torch::kInt64);
std::cout << (x.gather(0, g)) << std::endl << std::endl;
// std::cout << (torch::gather(x, 0, g, false)) << std::endl << std::endl;


x =
  0   1   2   3
  4   5   6   7
  8   9  10  11
[ CPUFloatType{3,4} ]

<<< tensor.index_select >>>
 1
 2
[ CPULongType{2} ]

x.index_select(dim = 0, index = idx) =
  4   5   6   7
  8   9  10  11
[ CPUFloatType{2,4} ]

x.index_select(dim = 1, index = idx) =
  1   2
  5   6
  9  10
[ CPUFloatType{3,2} ]

<<< tensor.masked_select >>>
 0  0  0  0
 0  0  1  1
 1  1  1  1
[ CPUBoolType{3,4} ]

x.masked_select(mask = mask) =
  6
  7
  8
  9
 10
 11
[ CPUFloatType{6} ]

<<< tensor.nonzero >>>
注意，返回值是非零元素下标，即x,y 
x.nonzero() =
 0  1
 0  2
 0  3
 1  0
 1  1
 1  2
 1  3
 2  0
 2  1
 2  2
 2  3
[ CPULongType{11,2} ]

<<< tensor.gather >>>
注意，index tensor必须指明类型为int64
 4  5
 4  5
[ CPUFloatType{2,2} ]



## 2.3 广播

In [16]:
torch::Tensor a = torch::ones({1,3});
torch::Tensor b = torch::ones({3,1});

b = b + 1;

printT((a+b));

(a+b) = 
 3  3  3
 3  3  3
 3  3  3
[ CPUFloatType{3,3} ]
<<--->>




## 2.4 改变形状

In [17]:
/* *
 *  Change shapes
 */
constexpr int w = 3;
constexpr int h = 5;
torch::Tensor x = torch::zeros({h,w});

for (int i = 0; i < h; i++) {
    for (int j = 0; j < w; j++) {
        x[i][j] = i*w+j;
    }
}

printT(x);

torch::Tensor y = x.view({w, -1});
printT(y);


/*
 * resize_(...) 参见 ATen/native/Resize.cpp
 */
printT(x.resize_({1, w*h}));


x = 
  0   1   2
  3   4   5
  6   7   8
  9  10  11
 12  13  14
[ CPUFloatType{5,3} ]
<<--->>

y = 
  0   1   2   3   4
  5   6   7   8   9
 10  11  12  13  14
[ CPUFloatType{3,5} ]
<<--->>

x.resize_({1, w*h}) = 
  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14
[ CPUFloatType{1,15} ]
<<--->>

